inherit_gem: { rubocop-rails-omakase: rubocop.yml }

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Max: 50
  Exclude:
    - 'spec/**/*'

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'node_modules/**/*'